version: '3.8'
name: 'rinha-backend-spring-local'

services:
  postgres-db:
    image: postgres:latest
    container_name: rinha-backend-db
    user: postgres
    command: 'postgres -c max_connections=600 -c shared_buffers=512MB -c synchronous_commit=off -c fsync=off'
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - "6553:5432"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '500M'
    volumes:
      - ./rinha-backend/src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgresql.conf:/docker-entrypoint-initdb.d/postgresql.conf
    networks:
      - app-network
  cache:
    hostname: cache
    image: redis:latest
    ports:
      - '6379:6379'
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '300M'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    networks:
      - app-network

networks:
  app-network: