version: '3.8'
name: 'rinha'

services:
  api-1: &api
    image: rodriginhu/rinha-backend
    hostname: api-1
    environment:
      - SERVER_PORT=8080
      - DATABASE_URL=jdbc:postgresql://pgbouncer:6432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - REDIS_HOST=cache
    depends_on:
      pgbouncer:
        condition: service_healthy
      cache:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.45'
          memory: '600M'
    networks:
      app-network:

  api-2:
    <<: *api
    hostname: api-2

  pgbouncer:
    image: edoburu/pgbouncer
    container_name: pgbouncer
    ports:
      - "6432:6432"
    environment:
      - PGBOUNCER_INI_FILE=/etc/pgbouncer/pgbouncer.ini
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "postgres", "-p", "5432", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - ./pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini
      - ./userlist.txt:/etc/pgbouncer/userlist.txt
    deploy:
      resources:
        limits:
          cpus: '0.05'
          memory: '100M'
    networks:
      app-network:

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api-1
      - api-2
    ports:
      - '9999:9999'
    deploy:
      resources:
        limits:
          cpus: '0.05'
          memory: '550M'
    networks:
      - app-network

  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    command:
      'postgres -c max_connections=400 -c shared_buffers=512MB -c effective_cache_size=500MB -c log_min_messages=FATAL && sh -c psql -h pgbouncer -p 6432 -U postgres -d postgres -c "SELECT 1"'' '
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -p 5432 -U postgres" ]
      interval: 3s
      timeout: 5s
      retries: 10
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '1200M'
    volumes:
      - ./rinha-backend/src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgresql.conf:/docker-entrypoint-initdb.d/postgresql.conf
    ports:
      - '6553:5432'
    networks:
      - app-network

  cache:
    hostname: cache
    image: redis:latest
    ports:
      - '6379:6379'
    deploy:
      resources:
        limits:
          cpus: '0.05'
          memory: '50M'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    command:
      'redis-server --save "" --appendonly no'

    healthcheck:
      test: [ 'CMD', 'redis-cli', '--raw', 'incr', 'ping' ]
    networks:
      - app-network

networks:
  app-network: